### ISSUE TITLE
[Antidote Verifier] Input string was not in a correct format.

### ISSUE THREAD

**Issue by mornir** [sdl/Sdl-Community#35]
Hi,
First I'd like to thank you for this awesome plugin! It saves me a lot of time!

For some translations, I get the following error when I activate the Antidote Verifier plugin:

`<SDLErrorDetails time="8/28/2017 4:43:32 PM">
  <ErrorMessage>Input string was not in a correct format.</ErrorMessage>
  <Exception>
    <Type>System.FormatException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</Type>
    <HelpLink />
    <Source>mscorlib</Source>
    <HResult>-2146233033</HResult>
    <StackTrace><![CDATA[   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at Sdl.Community.AntidoteVerifier.EditorService.Initialize()
   at Sdl.Community.AntidoteVerifier.EditorService..ctor(Document document)
   at Sdl.Community.AntidoteVerifier.AntidoteCorrectorAction.Execute()
   at Sdl.Desktop.IntegrationApi.AbstractAction.Sdl.Desktop.IntegrationApi.Extensions.Internal.IAction.Execute()
   at Sdl.Desktop.IntegrationApi.Internal.Adaptors.InternalActionAdaptor.Execute()
   at Sdl.Desktop.Platform.Implementation.CommandBars.ActionService.<>c__DisplayClass3.<ExecuteAction>b__2()
   at Sdl.Desktop.Platform.Implementation.Services.Log.Resources(Object message, Action action)
   at Sdl.Desktop.Platform.Implementation.CommandBars.ActionService.ExecuteAction(IAction action, ActionOrigin origin, Boolean allowToggle)
   at Sdl.Desktop.Platform.WinForms.IgCommandBarAction.Execute()
   at Sdl.Desktop.Platform.WinForms.IgCommandBarAction._lazyButtonTool_ToolClick(Object sender, ToolClickEventArgs e)
   at Infragistics.Win.UltraWinToolbars.ToolBase.OnToolClick(ToolClickEventArgs e)
   at Infragistics.Win.UltraWinToolbars.UltraToolbarsManager.OnToolClick(ToolClickEventArgs e)
   at Infragistics.Win.UltraWinToolbars.UltraToolbarsManager.FireEvent(ToolbarEventIds id, EventArgs e)
   at Infragistics.Win.UltraWinToolbars.ToolBase.OnToolClick()
   at Infragistics.Win.UltraWinToolbars.ToolMenuItem.OnClick()
   at Infragistics.Win.UltraWinToolbars.PopupMenuItemUIElement.DoClickProcessing(MouseEventArgs e)
   at Infragistics.Win.UltraWinToolbars.PopupMenuItemUIElement.OnMouseUp(MouseEventArgs e)
   at Infragistics.Win.TextUIElementBase.OnMouseUp(MouseEventArgs e)
   at Infragistics.Win.ControlUIElementBase.ProcessMouseUpHelper(Object sender, MouseEventArgs e)
   at Infragistics.Win.ControlUIElementBase.ProcessMouseUp(Object sender, MouseEventArgs e)
   at Infragistics.Win.Utilities.ProcessEvent(Control control, ProcessEvent eventToProcess, EventArgs e)
   at Infragistics.Win.UltraWinToolbars.PopupControlBase.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)]]></StackTrace>
  </Exception>
  <Environment>
    <ProductName>SDL Trados Studio</ProductName>
    <ProductVersion>14.0.0.0</ProductVersion>
    <EntryAssemblyFileVersion>14.0.5889.5</EntryAssemblyFileVersion>
    <OperatingSystem>Microsoft Windows 7 Enterprise </OperatingSystem>
    <ServicePack>Service Pack 1</ServicePack>
    <OperatingSystemLanguage>1031</OperatingSystemLanguage>
    <CodePage>1252</CodePage>
    <DotNetFrameWork>4.0.30319.36403</DotNetFrameWork>
    <ConnectedToNetwork>True</ConnectedToNetwork>
    <PhysicalMemory>8260720 MB</PhysicalMemory>
  </Environment>
</SDLErrorDetails>`

Do you know what the problem is? I don't know if it is relevant, but that particular translation contains a tag as the first character of the first segment, but the error keeps occurring even after I removed that tag in the target language.

**Comment by mornir** [comment]
I haven't run into that bug for more than one year. I guess an update fixed the issue.
